# Generated by Django 4.2 on 2024-05-04 18:16

import annonce.models
import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrosserie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Couleurs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Energie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Marque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
            ],
        ),
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('marque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.marque')),
            ],
        ),
        migrations.CreateModel(
            name='Sellerie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Transmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vente_type', models.CharField(choices=[('regulier', 'Prix régulier'), ('leasing', 'Sous leasing'), ('non_dedouiane', 'Non dédouiane')], max_length=20)),
                ('prix', models.IntegerField()),
                ('CESSION_PRICE', models.IntegerField(blank=True, null=True)),
                ('LOYER_PRIX', models.IntegerField(blank=True, null=True)),
                ('MENSUALITES', models.IntegerField(blank=True, null=True)),
                ('FRAIS_DE_DOUANE', models.IntegerField(blank=True, null=True)),
                ('CESSION_PRIX', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Voiture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fenitions', models.TextField(max_length=150, null=True)),
                ('about', models.TextField(blank=True)),
                ('kilometrage', models.IntegerField()),
                ('mise_en_circulation', models.DateField()),
                ('boite', models.CharField(choices=[('Manuelle', 'Manuelle'), ('Automatique', 'Automatique')], max_length=50)),
                ('nombre_de_portes', models.IntegerField()),
                ('nombre_de_places', models.IntegerField()),
                ('cylidre_cm3', models.IntegerField()),
                ('carrosserie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.carrosserie')),
                ('couleur_externe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exterieur_voitures', to='annonce.couleurs')),
                ('couleur_interieur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interieur_voitures', to='annonce.couleurs')),
                ('energie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.energie')),
                ('generation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.generation')),
                ('marque', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.marque')),
                ('modele', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.modele')),
                ('sellerie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.sellerie')),
                ('transmission', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='annonce.transmission')),
            ],
        ),
        migrations.AddField(
            model_name='generation',
            name='modele',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.modele'),
        ),
        migrations.CreateModel(
            name='Car_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, null=True, validators=[annonce.models.file_validation], verbose_name='Image')),
                ('voiture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='annonce.voiture')),
            ],
        ),
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adresss', models.TextField()),
                ('telephone', models.IntegerField()),
                ('gouvernoment', models.CharField(choices=[('Ariana', 'Ariana'), ('Béja', 'Béja'), ('Ben Arous', 'Ben Arous'), ('Bizerte', 'Bizerte'), ('Gabès', 'Gabès'), ('Gafsa', 'Gafsa'), ('Jendouba', 'Jendouba'), ('Kairouan', 'Kairouan'), ('Kasserine', 'Kasserine'), ('Kébili', 'Kébili'), ('La Manouba', 'La Manouba'), ('Le Kef', 'Le Kef'), ('Mahdia', 'Mahdia'), ('Médenine', 'Médenine'), ('Monastir', 'Monastir'), ('Nabeul', 'Nabeul'), ('Sfax', 'Sfax'), ('Sidi Bouzid', 'Sidi Bouzid'), ('Siliana', 'Siliana'), ('Sousse', 'Sousse'), ('Tataouine', 'Tataouine'), ('Tozeur', 'Tozeur'), ('Tunis', 'Tunis'), ('Zaghouan', 'Zaghouan')], max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='annonce.vente')),
                ('voitures', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.voiture')),
            ],
        ),
    ]
