# Generated by Django 4.2 on 2024-05-04 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gouvernorat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='annonce',
            name='gouvernoment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='annonce.gouvernorat'),
        ),
    ]
