# Generated by Django 4.2 on 2024-05-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('annonce', '0002_gouvernorat_alter_annonce_gouvernoment'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonce',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='voiture',
            name='fenitions',
            field=models.TextField(blank=True, max_length=150, null=True),
        ),
    ]
